/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : SquareWave.h
**     Project     : ProcessorExpert
**     Processor   : MCF51JM32VLD
**     Component   : BitIO
**     Version     : Component 02.075, Driver 03.14, CPU db: 3.00.062
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2012-11-27, 16:45, # CodeGen: 8
**     Abstract    :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings    :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       14            |  PTE6_SPSCK1
**             ----------------------------------------------------
**
**         Port name                   : PTE
**
**         Bit number (in port)        : 6
**         Bit mask of the port        : 0x0040
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTED      [0xFFFF8008]
**         Port control register       : PTEDD     [0xFFFF8009]
**
**         Optimization for            : speed
**     Contents    :
**         GetVal - bool SquareWave_GetVal(void);
**         PutVal - void SquareWave_PutVal(bool Val);
**         ClrVal - void SquareWave_ClrVal(void);
**         SetVal - void SquareWave_SetVal(void);
**         NegVal - void SquareWave_NegVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef SquareWave_H_
#define SquareWave_H_

/* MODULE SquareWave. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  SquareWave_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define SquareWave_GetVal() ( \
    (bool)((getReg8(PTED) & 0x40U))    /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  SquareWave_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void SquareWave_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  SquareWave_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define SquareWave_ClrVal() ( \
    (void)clrReg8Bits(PTED, 0x40U)     /* PTED6=0x00U */ \
  )

/*
** ===================================================================
**     Method      :  SquareWave_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define SquareWave_SetVal() ( \
    (void)setReg8Bits(PTED, 0x40U)     /* PTED6=0x01U */ \
  )

/*
** ===================================================================
**     Method      :  SquareWave_NegVal (component BitIO)
**
**     Description :
**         This method negates (inverts) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define SquareWave_NegVal() ( \
    (void)invertReg8Bits(PTED, 0x40U)  /* PTED6=invert */ \
  )



/* END SquareWave. */
#endif /* #ifndef __SquareWave_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 5.3 [05.01]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
