/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : WaveSwitcher.h
**     Project     : ProcessorExpert
**     Processor   : MCF51JM32VLD
**     Component   : KBI
**     Version     : Component 01.096, Driver 01.25, CPU db: 3.00.062
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2012-11-27, 17:11, # CodeGen: 15
**     Abstract    :
**         This component "KBI" implements the Freescale Keyboard 
**         Interrupt Module (KBI/KBD) which allows to catch events 
**         on selected external pins. These pins share one KBI/KBD 
**         interrupt which can be caused by events on the pins.
**     Settings    :
**         Keyboard                    : KBI1 
**         Used pins           
**         Pin 0                       : PTG1_KBIP1
**         Pull resistor               : up
**         Generate interrupt on       : falling
**         Interrupt service           : Enabled
**         Interrupt                   : Vkeyboard
**         Interrupt Priority          : 270
**         Enable in init. code        : Yes
**         Events enabled in init.     : Yes
**     Contents    :
**         GetVal  - byte WaveSwitcher_GetVal(void);
**         SetEdge - byte WaveSwitcher_SetEdge(byte edge);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __WaveSwitcher
#define __WaveSwitcher

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"

/* MODULE WaveSwitcher. */

#include "Cpu.h"

/* PUBLISHED CONSTANTS for using together with GetVal method  */
#define WaveSwitcher_NUM_PIN0 0x01U /* Mask of Pin0 */

/* PUBLISHED CONSTANTS for enabled pins */
#define WaveSwitcher_PIN_SIGNAL0 0x02U  /* Mask of Pin0*/

/* Deprecated */
#define PinSignal0            0x01U


void WaveSwitcher_Init(void);
/*
** ===================================================================
**     Method      :  WaveSwitcher_Init (component KBI)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void WaveSwitcher_Interrupt(void);
/*
** ===================================================================
**     Method      :  WaveSwitcher_Interrupt (component KBI)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#define WaveSwitcher_GetVal() \
  ((byte)((PTGD & 0x02U) >> 1))

/*
** ===================================================================
**     Method      :  WaveSwitcher_GetVal (component KBI)
**
**     Description :
**         Returns the value of pins
**     Parameters  : None
**     Returns     :
**         ---             - The value of associated pins (bits ordered
**                           according to the component list of pins)
** ===================================================================
*/

byte WaveSwitcher_SetEdge(byte edge);
/*
** ===================================================================
**     Method      :  WaveSwitcher_SetEdge (component KBI)
**
**     Description :
**         Sets the sensitive edge. If all selected pins don't have the
**         same edge setting possibility, the method allows to set only
**         those edges that are common (possible to set for all
**         selected pins).
**     Parameters  :
**         NAME            - DESCRIPTION
**         edge            - Edge type:
**                           0 - falling edge
**                           1 - rising edge
**                           2 - both edges
**                           3 - low level
**                           4 - high level
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Value is out of range
** ===================================================================
*/


/* END WaveSwitcher. */

#endif /* ifndef __WaveSwitcher */
/*
** ###################################################################
**
**     This file was created by Processor Expert 5.3 [05.01]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
