/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : WaveSwitcher.c
**     Project     : ProcessorExpert
**     Processor   : MCF51JM32VLD
**     Component   : KBI
**     Version     : Component 01.096, Driver 01.25, CPU db: 3.00.062
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2012-11-27, 17:11, # CodeGen: 15
**     Abstract    :
**         This component "KBI" implements the Freescale Keyboard 
**         Interrupt Module (KBI/KBD) which allows to catch events 
**         on selected external pins. These pins share one KBI/KBD 
**         interrupt which can be caused by events on the pins.
**     Settings    :
**         Keyboard                    : KBI1 
**         Used pins           
**         Pin 0                       : PTG1_KBIP1
**         Pull resistor               : up
**         Generate interrupt on       : falling
**         Interrupt service           : Enabled
**         Interrupt                   : Vkeyboard
**         Interrupt Priority          : 270
**         Enable in init. code        : Yes
**         Events enabled in init.     : Yes
**     Contents    :
**         GetVal  - byte WaveSwitcher_GetVal(void);
**         SetEdge - byte WaveSwitcher_SetEdge(byte edge);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE WaveSwitcher. */

#include "Events.h"
#include "WaveSwitcher.h"



/*
** ===================================================================
**     Event       :  WaveSwitcher_OnInterrupt (module Events)
**
**     Component   :  WaveSwitcher [KBI]
**     Description :
**         This event is called when the active signal edge/level
**         occurs. This event is enabled only if <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
ISR(WaveSwitcher_Interrupt)
{
  KBI1SC_KBACK = 0x01U;                /* Clear the interrupt flag */
  WaveSwitcher_OnInterrupt();          /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  WaveSwitcher_GetVal (component KBI)
**
**     Description :
**         Returns the value of pins
**     Parameters  : None
**     Returns     :
**         ---             - The value of associated pins (bits ordered
**                           according to the component list of pins)
** ===================================================================
*/
/*
byte WaveSwitcher_GetVal(void)

**      This method is implemented as macro. See WaveSwitcher.h file.      **
*/

/*
** ===================================================================
**     Method      :  WaveSwitcher_SetEdge (component KBI)
**
**     Description :
**         Sets the sensitive edge. If all selected pins don't have the
**         same edge setting possibility, the method allows to set only
**         those edges that are common (possible to set for all
**         selected pins).
**     Parameters  :
**         NAME            - DESCRIPTION
**         edge            - Edge type:
**                           0 - falling edge
**                           1 - rising edge
**                           2 - both edges
**                           3 - low level
**                           4 - high level
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Value is out of range
** ===================================================================
*/
byte WaveSwitcher_SetEdge(byte edge)
{
  if ((edge > 4U) || (edge == 2U)) {   /* If parameter is out of range */
    return ERR_RANGE;                  /* ....then return error */
  }
  KBI1SC_KBIE = 0U;                    /* Disable device */
  if ((edge == 3U) || (edge == 4U)) {  /* Level selected */
    KBI1SC_KBIMOD = 0x01U;             /* Set the level */
    if (edge == 3U) {
    /* KBI1ES: KBEDG1=0 */
      KBI1ES &= (byte)(~(byte)0x02U);  /* The low level */
    }
    else {
    /* KBI1ES: KBEDG1=1 */
      KBI1ES |= 0x02U;                 /* The high level */
    }
  }
  else {                               /* Edge selected */
    KBI1SC_KBIMOD = 0U;                /* Set the edge */
    if (edge == 0U) {
    /* KBI1ES: KBEDG1=0 */
      KBI1ES &= (byte)(~(byte)0x02U);  /* The falling edge */
    }
    else {
    /* KBI1ES: KBEDG1=1 */
      KBI1ES |= 0x02U;                 /* The rising edge */
    }
  }
  KBI1SC_KBACK = 0x01U;                /* Clear the interrupt flag */
  KBI1SC_KBIE = 0x01U;                 /* Enable device */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  WaveSwitcher_Init (component KBI)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void WaveSwitcher_Init(void)
{
  /* KBI1ES: KBEDG7=0,KBEDG6=0,KBEDG5=0,KBEDG4=0,KBEDG3=0,KBEDG2=0,KBEDG1=0,KBEDG0=0 */
  setReg8(KBI1ES, 0x00U);               
  /* KBI1SC: ??=0,??=0,??=0,??=0,KBF=0,KBACK=0,KBIE=0,KBIMOD=0 */
  setReg8(KBI1SC, 0x00U);               
  /* KBI1PE: KBIPE1=1 */
  setReg8Bits(KBI1PE, 0x02U);          /* Enable appropriate interrupt pin(s) */ 
  /* KBI1SC: KBACK=1 */
  setReg8Bits(KBI1SC, 0x04U);          /* Clear the interrupt flag */ 
  /* KBI1SC: KBIE=1 */
  setReg8Bits(KBI1SC, 0x02U);          /* Enable interrupts */ 
}

/* END WaveSwitcher. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 5.3 [05.01]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
